### ISSUE TITLE
regenerate is broken ?

### ISSUE THREAD

**Issue by grosser** [byroot/bootscale#1]
```
/Users/mgrosser/Code/zendesk/zendesk/vendor/bundle/ruby/2.1.0/gems/bootscale-0.2.1/lib/bootscale/entry.rb:15:in `initialize': undefined method `end_with?' for #<Pathname:0x007f95d20626c8> (NoMethodError)
    from /Users/mgrosser/Code/zendesk/zendesk/vendor/bundle/ruby/2.1.0/gems/bootscale-0.2.1/lib/bootscale/cache_builder.rb:10:in `new'
    from /Users/mgrosser/Code/zendesk/zendesk/vendor/bundle/ruby/2.1.0/gems/bootscale-0.2.1/lib/bootscale/cache_builder.rb:10:in `block (2 levels) in generate'
    from /Users/mgrosser/Code/zendesk/zendesk/vendor/bundle/ruby/2.1.0/gems/bootscale-0.2.1/lib/bootscale/cache_builder.rb:10:in `fetch'
    from /Users/mgrosser/Code/zendesk/zendesk/vendor/bundle/ruby/2.1.0/gems/bootscale-0.2.1/lib/bootscale/cache_builder.rb:10:in `block in generate'
    from /Users/mgrosser/Code/zendesk/zendesk/vendor/bundle/ruby/2.1.0/gems/bootscale-0.2.1/lib/bootscale/cache_builder.rb:10:in `map'
    from /Users/mgrosser/Code/zendesk/zendesk/vendor/bundle/ruby/2.1.0/gems/bootscale-0.2.1/lib/bootscale/cache_builder.rb:10:in `generate'
    from /Users/mgrosser/Code/zendesk/zendesk/vendor/bundle/ruby/2.1.0/gems/bootscale-0.2.1/lib/bootscale.rb:26:in `regenerate'
    from /Users/mgrosser/Code/zendesk/zendesk/config/application.rb:295:in `blo
```

**Comment by byroot** [comment]
Yeah I fixed an hour ago :) https://github.com/byroot/bootscale/commit/e2b88e1890d89f20e0706bd6579fb1301d38810c#diff-472b733fe2076a212db53cf3234756f7R9

**Comment by grosser** [comment]
needs tests ;)

**Comment by grosser** [comment]
that was on 0.2.1 and that's still the lastest ...

**Comment by byroot** [comment]
Hum, that's weird. And yes it definitely need test. I think I'll add a dummy rails app and boot it.

**Comment by byroot** [comment]
@grosser escuse me but do you still have

**Comment by byroot** [comment]
Ok, given, you backtrace it seems you have a `Pathname` instance in your `$LOAD_PATH`. That is not recommended (it disable some MRI internal caching), but I think we should support it anyway.

I'll implement a test and a fix.

**Comment by grosser** [comment]
Nah idk ... maybe better to blow up with a descriptive error ... or warn
... so the root cause gets fixed

**Comment by byroot** [comment]
I would think so too, but if the issue comes from a gem, most people will have a hard time figuring out.

Also calling `to_s` on a String is almost free, so the downsides are really small.

**Comment by byroot** [comment]
I just released a `0.2.2` for you.

**Comment by grosser** [comment]
thx!

**Comment by grosser** [comment]
Making a bunch of PRs to get rid of PathName in load_path, do you have any source for "it disables some MRI internal caching" ?

**Comment by byroot** [comment]
Sure let me grep MRI again :)

**Comment by byroot** [comment]
Here you go: https://github.com/ruby/ruby/blob/457ca4dc29d9047e7547a02acb73845edce606a3/load.c#L43-L47
