### ISSUE TITLE
inefficient memory use

### ISSUE THREAD

**Issue by grosser** [byroot/bootscale#14]
atm we hold 2 copies of every load-paths files
- in builds `@entries`
- in actually used `cache`

ideally we would have 1 ... maybe pass the cache into regenerate and just add instead of building a new hash and throwing away the old one

**Comment by grosser** [comment]
@byroot

**Comment by byroot** [comment]
Hum, the thing is that `@entries` is only built on misses. So once the cache is warm, it will stay empty.

Is it really a big problem?

**Comment by grosser** [comment]
Looks to me like `@entries` is getting prefilled with everything / we cache `flat_map(&:features)`
Not really a big issue, but I'd like to avoid it anyway, just wanted to get your feedback before I do a PR

**Comment by byroot** [comment]
So my reasoning for `@entries` was that:
- On cache hit it's just not built
- On cache miss, we are likely to build the cache twice (1 for bundler, 1 after Rails initialization)
- A bit of ram on cache misses is less costly that crawling the disk again.

If theses really bother you, I guess we can add a `Bootscale.cleanup` method to clear them once we are sure we won't need them anymore.
