### ISSUE TITLE
entry / features is confusing

### ISSUE THREAD

**Issue by grosser** [byroot/bootscale#15]
entry == load_path
features == file_map ?

**Comment by grosser** [comment]
@byroot

**Comment by byroot** [comment]
Yes entry is a LOAD_PATH entry, and Feature is a requirable file. It's the terminology MRI uses, see `$LOADED_FEATURES`

**Comment by grosser** [comment]
hmm good reason I guess ... LoadPath and file_map still seem more intuitive to me, how about you ?

**Comment by byroot** [comment]
Well, `LoadPath` makes me think of a list of paths.

As for  `file_map`, file is a bit too vague. I would be ok with `requireables` or something along those lines.
