### ISSUE TITLE
Bootscale/activesupport?

### ISSUE THREAD

**Issue by byroot** [byroot/bootscale#26]
Application boot before bootscale:
<img width="688" alt="capture d ecran 2015-08-27 a 18 36 45" src="https://cloud.githubusercontent.com/assets/44640/9534948/ba04af5a-4cea-11e5-8860-d021238174ba.png">

And after bootscale:
<img width="685" alt="capture d ecran 2015-08-27 a 18 37 10" src="https://cloud.githubusercontent.com/assets/44640/9534949/be135b0a-4cea-11e5-9f0e-2508263859a9.png">

There isn't probably much more we can do to speedup `require`, but `search_for_file` could be patched to lookup into `Bootscale`:

<img width="573" alt="capture d ecran 2015-08-27 a 18 38 59" src="https://cloud.githubusercontent.com/assets/44640/9534980/f7dbd97a-4cea-11e5-924e-205be4f39f04.png">

Also I assume most potential users of bootscale are Rails users. It could be nice to see if the post set_load_path initializer could be set automatically.

Upstream PRs:
- `AS::Dependencies.loadable_constants_for_path` https://github.com/rails/rails/pull/21411

**Comment by grosser** [comment]
that sounds good :)

grep for autoload_paths + load_paths in rails repo ... maybe there is more :D

**Comment by byroot** [comment]
So I instrumented `search_for_file`, and while it's called a lot `~1700` times during boot and code reload for me. Since there isn't that much autoload_paths (`49`), in the end it only account for about `100ms`.

And those numbers are an extreme case IMO.

A few facts: 
- This is mostly used in development mode
- Most calls are misses
- If we cache misses, then you need to reload your server when you add a new file, so it break the development flow
- If we don't cache misses, then we barely save `10%` of those `100ms`
- It would require a separate cache from the `$LOAD_PATH` one for correctness

All those points above make me believe it's not worth caching `search_for_file`. I'm still looking for other perf gains in there though.
