### ISSUE TITLE
MessagePack serializer and relative paths can't work together

### ISSUE THREAD

**Issue by byroot** [byroot/bootscale#29]
It just hit me that MessagePack serialize symbols as strings:

``` ruby
>> MessagePack.load(MessagePack.dump(:relative))
=> "relative"
```

So if someone were to use MessagePack and happen to have relative paths at the same time, the cache will be corrupted.

**Comment by grosser** [comment]
ah great ... so store a magic number instead ?
`RELATIVE = 3423424234235345345` and then check `path == RELATIVE`

**Comment by byroot** [comment]
Hum. Yeah doesn't even need to be a magic number. Can be `true`, `false` or `nil`.

**Comment by byroot** [comment]
I think false will do.
