### ISSUE TITLE
drop messagepack

### ISSUE THREAD

**Issue by grosser** [byroot/bootscale#4]
it's about 2x faster than Marshal, but that's just 10ms or so we save ... and would be 1 less dependency ?

alternatively (still not worth the few ms saved ?): when messagepack is installed use it, otherwise don't -> no longer a runtime dependency

**Comment by grosser** [comment]
@byroot

**Comment by byroot** [comment]
I'm totally ok with this. I would merge a PR with this change. Otherwise I'll implement it sometimes this week for sure.

The difference is quite big though, even if it's only 2-2.5X:

```
Calculating -------------------------------------
             marshal     3.000  i/100ms
             msgpack     8.000  i/100ms
-------------------------------------------------
             marshal     37.836  (±15.9%) i/s -    186.000 
             msgpack     82.908  (±12.1%) i/s -    416.000 
```

So I really recommend using msgpack.

**Comment by grosser** [comment]
require is 2ms -> would only pay if (loading msgpack + loading pack) <
(loading pack with marshal)

which it is not for our app ... and I'd guess for most other apps it's not
either ... can you benchmark how long it takes to load your pack with
msgpack vs marshal ?

**Comment by byroot** [comment]
> can you benchmark how long it takes to load your pack with
> msgpack vs marshal ?

It's the benchmark I posted above `12ms` for MessagePack and `26ms` for Marshal.

That being said Shopify's Gemfile is huge and it might not make sense for smaller app:

``` ruby
>> $LOAD_PATH.size
=> 452
>> Bootscale.cache.size
=> 12245
```

Here's the benchmark I used:

``` ruby
require 'msgpack'
require 'benchmark/ips'

msgpack = File.read('tmp/bootscale-b20873fb90ee9b404440e1ff68b79f1e.msgpack')
marshal = Marshal.dump(MessagePack.load(msgpack))

Benchmark.ips do |x|
  x.report('marshal') { Marshal.load(marshal) }
  x.report('msgpack') { MessagePack.load(msgpack) }
end
```

If you'd like to test it on your app and find out that msgpack is not advantageous for everyone, I'll be happy to make it optional.

**Comment by grosser** [comment]
Damn ... got the decimal place wrong :D

Load paths 450 / Size 14356
0.029302 dump
0.042364 load

so yeah even with require it would be faster ... but I'll still try to get
rid of the dependency :)

now I just need to find and excuse to install 3 more gems ... not going to
let shopify beat us ;)

**Comment by byroot** [comment]
Fixed in https://github.com/byroot/bootscale/pull/9
